services:
  - type: web
    name: website-engine-frontend
    env: node
    plan: free
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: API_BASE_URL
        sync: false
      - key: PORT
        value: 3000
